//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblWorker()
        {
            this.tblWorkers1 = new HashSet<tblWorker>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> IDCardNumber { get; set; }
        public string JMBG { get; set; }
        public string Gender { get; set; }
        public Nullable<int> PhoneNumber { get; set; }
        public Nullable<int> FKSector { get; set; }
        public Nullable<int> FKLocation { get; set; }
        public Nullable<int> FKManager { get; set; }
    
        public virtual tblLocation tblLocation { get; set; }
        public virtual tblSector tblSector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWorker> tblWorkers1 { get; set; }
        public virtual tblWorker tblWorker1 { get; set; }
    }
}
